[metadata]
addr = 0x8809048
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_SET_CHAR_OBJ_BUY_ICE_CREAM_CHAR_CHAR_STORE_STATUS"
addr = 0x8809048
