[metadata]
addr = 0x8884408
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_UNLOAD_NON_STANDARD_PED_ANIMATIONS"
addr = 0x8884408
