[metadata]
addr = 0x88875f4
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_SET_AMOUNTS_EMPIRE_SITES_OWNED_VANCE_CHOLO_SHARKS_BIKERS"
addr = 0x88875f4
