[metadata]
addr = 0x8884f94
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_UNKNOWN_CHAR_COMMAND_8377_VALUE_STORE_TO"
addr = 0x8884f94
