[metadata]
addr = 0x8886d48
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_REGISTER_WATERSPORTS_TIME_COURSE_TIME"
addr = 0x8886d48
