[metadata]
addr = 0x893354c
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_GET_EMPIRE_FROM_BUILDING_MODEL_HASH_STORE_TO"
addr = 0x893354c
