[metadata]
addr = 0x8946088
size = 0x48

[header]
last_change = 2023-11-15T18:09:49.818915Z
name = "CVisibilityComponents::RenderVehicleLoDetailCB_Boat_Far"
addr = 0x8946088
type = "int"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4
