[metadata]
addr = 0x8abc194
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_TERMINATE_ALL_SCRIPTS_WITH_THIS_NAME"
addr = 0x8abc194
