[metadata]
addr = 0x8ac7238
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_UNKNOWN_IS_SPECIFIED_AREA_FOR_CHAR_SET_UP"
addr = 0x8ac7238
