[metadata]
addr = 0x8aeb3a0
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_UNKNOWN_GET_OBJECT_FROM_CAR_COMMAND_8457_STORE_OBJECT_TO"
addr = 0x8aeb3a0
