[metadata]
addr = 0x8ae5224
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_IS_CAR_STOPPED_IN_AREA_3D_CORNERA_CORNERB_SPHERE"
addr = 0x8ae5224
