[metadata]
addr = 0x8af41b8
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_DISPLAY_ONSCREEN_COUNTER_WITH_TWO_NUMBERS_PLACE_NUMBER_OF_LEVELS_UNK3_UNK4_STRING_PROGRESS_SUBJECT"
addr = 0x8af41b8
