[metadata]
addr = 0x8af03d0
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_SET_TEXT_COLOUR_RGB_RED_RGB_GREEN_RGB_BLUE_OPACITY"
addr = 0x8af03d0
