[metadata]
addr = 0x08b2c2ac
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_GET_CHAR_WEAPON_IN_SLOT_SLOT_STORE_WEAPON_TO_AMMO_TO_MODEL_TO"
addr = 0x08b2c2ac
