[metadata]
addr = 0x08b2e760
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_GET_RANDOM_CHAR_IN_AREA_NO_CHECKS_FROM_TO_STORE_TO"
addr = 0x08b2e760
