[metadata]
addr = 0x08b30934
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_UNKNOWN_ATTACHED_PLAYER_SET_ANGLE_COMMAND_1969_ANGLE"
addr = 0x08b30934
