[metadata]
addr = 0x8b3c030
size = 0x320
last_change = 2023-11-15T18:12:14.424393Z

[header]
last_change = 2023-11-15T18:09:52.406367Z
name = "CCutsceneMgr::LoadCutsceneData_postload"
addr = 0x8b3c030
type = "void"

[stack_vars.-0x4c]
offset = 0x0
name = "v15"
type = "int"
size = 0x4
addr = 0x8b3c030

[stack_vars.-0x48]
offset = 0x4
name = "v16"
type = "int"
size = 0x4
addr = 0x8b3c030

[stack_vars.-0x44]
offset = 0x8
name = "v17"
type = "int[2]"
size = 0x8
addr = 0x8b3c030

[stack_vars.-0x3c]
offset = 0x10
name = "v18"
type = "int"
size = 0x4
addr = 0x8b3c030

[stack_vars.-0x38]
offset = 0x14
name = "v19"
type = "int[2]"
size = 0x8
addr = 0x8b3c030

[stack_vars.-0x30]
offset = 0x1c
name = "v20"
type = "int"
size = 0x4
addr = 0x8b3c030

[stack_vars.-0x2c]
offset = 0x20
name = "v21"
type = "const char *"
size = 0x4
addr = 0x8b3c030

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4
