[0x8baab84]
last_change = 2023-11-23T05:41:38.734434Z
addr = 0x8baab84
name = "ScriptSpace"
size = 0x4

[0x8be4918]
last_change = 2023-11-23T05:41:45.108411Z
addr = 0x8be4918
name = "ScriptsArray"
size = 0x10c00
